version: '3'
services:
  app_prod:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    image: webapp
    ports:
      - "3000:3000"
  app_dev:
    build:
      context: ./src
      dockerfile: ../DockerfileDev.dockerfile
    image: webapp
    ports:
      - "3000:3000"