name: Cypress Front End tests

on:
  push:
  pull_request:
    types: [created, labeled]

jobs:
  check_for_ui_ux_label:
    runs-on: ubuntu-latest
    name: Check for the UI/UX Label
    outputs:
      is_ui_ux_label_present: ${{ steps.check_pr_labels.outputs.result }} 
    steps: 
      - name: Check PR labels action step
        id: check_pr_labels
        uses: teamrocket77/check-pr-labels-on-push-action@v1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["UI/UX"]'
      - name: Is Label present
        run: |
          echo "${{ check_pr_labels.ouputs.results }}"

  cypress-run:
    name: Cypress run
    needs: check_for_ui_ux_label 
    if:  needs.check_for_ui_ux_label.outputs.is_ui_ux_label_present  == true
    runs-on: ubuntu-20.04
    steps:
      - name: Echo if labels were found
        run: |
          echo "${{ needs.check_for_ui_ux_label.outputs.is_ui_ux_label_present }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: src
          start: npm run dev
          spec: |
            cypress/**/frontend_tests/frontend.*js
          config: supportFile=false
      - name: Get Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: Front end Screenshots
          path: "**/cypress/screenshots/**/*.png"
