name: Cypress Front End tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [ opened, labeled, synchronize ]
    branches:
      - dev
      - main

permissions: read-all

jobs:
  check_for_ui_ux_label:
    runs-on: ubuntu-latest
    name: Check for the UI/UX Label
    outputs:
      is_ui_ux_label_present: ${{ steps.check_pr_labels.outputs.result }}
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: teamrocket77/check-pr-labels-on-push-action@c27d6443e146f69db177d5e8482e9ce337730c7e # pin@v1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["UI/UX"]'
      - name: Is label present
        run: |
          echo "${{ steps.check_pr_labels.outputs.result }}"

  cypress-run:
    name: Cypress run
    needs: check_for_ui_ux_label
    if: needs.check_for_ui_ux_label.outputs.is_ui_ux_label_present == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
      - name: Cypress run
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096 # pin@v5
        with:
          working-directory: src
          start: npm run dev
          spec: |
            cypress/**/frontend_tests/frontend.*js
          config: supportFile=false
      - name: Get Screenshots
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v3
        with:
          name: Front end Screenshots
          path: "**/cypress/screenshots/**/*.png"
