name: webapp-deployment-gcp
on:
  release:
    branches:
      - main # https://dscksu.dev
      - dev # https://preview.dscksu.dev
    types: [published]
  workflow_dispatch:

env:
  REPO_NAME: webapp
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.6.2
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_KEY }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}
      - name: Create Env File -> Source
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_GOOGLE_PROVIDER_CLIENT_ID: ${{ secrets.GOOGLE_PROVIDER_CLIENT_ID }}
          envkey_GOOGLE_PROVIDER_CLIENT_SECRET: ${{ secrets.GOOGLE_PROVIDER_CLIENT_SECRET }}
          envkey_GOOGLE_PROVIDER_AUTHORIZATION_URL: ${{ secrets.GOOGLE_PROVIDER_AUTHORIZATION_URL }}
          envkey_FIREBASE_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_ID }}
          envkey_FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          envkey_FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL }}
          envkey_DEBUG: true
          directory: src
          file_name: .env.production
          fail_on_empty: true
      - name: Source -> Docker Image
        run: |-
          DOCKER_BUILDKIT=1 docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
      - name: Docker Image -> Google Cloud Run
        run: |-
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
      - name: Deploy
        run: |-
          gcloud components install beta --quiet
          gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --project $CLOUD_RUN_PROJECT_ID \
            --platform managed \
            --region $CLOUD_RUN_REGION \
            --allow-unauthenticated \
            --quiet