name: Nav Bar Test YML
on:
  workflow_dispatch:
  push:
    branches:
      - 'nav_testing'
  pull_request:
    types: [ labeled ]

jobs:
  run_nav_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Get Repo
      - uses: actions/checkout@v3
