name: Nav Bar Test YML
on:
  workflow_dispatch:
  push:
    branches:
      - 'nav_testing'
  pull_request:
    types: [ labeled ]

jobs:
  run_nav_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: Install_Node_and_Packages
        run: |
            cd src/
            npm ci
            npx cypress run --spec ./cypress/e2e/nav_test.cy.js
