name: Nav Bar Test YML
on:
  workflow_dispatch:
  push:
    branches:
      - 'nav_testing'
  pull_request:
    types: [ labeled ]

jobs:
  run_nav_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Get Repo
      - uses: actions/checkout@v3

      - name: Get Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        run: npm ci
        # npx cypress run --spec ./cypress/e2e/nav_test.cy.js
