name: Screenshot actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'nav_testing'
  pull_request:
    types: [ labeled ]

jobs:
  get_screenshots:
    if: ${{ github.event.label.name == 'UI/UX' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Packages & Create Fixtures
        run: |
            npm ci
            npm i -g wait-on
            node ./cypress/prep_functions/page_fixture_creator.js

      - name: Start Server
        run: |
            npm run dev & wait-on http://localhost:3000

      - name: Run Screenshot test
        run: |
            npx cypress run --spec ./cypress/e2e/screenshots.cy.js

      - uses: actions/upload-artifact@v3
        with:
          name: Photos for recent PR GUI
          path: "**/cypress/screenshots/**/*.png"
