name: Screenshot actions
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'gui/**'
      - main
      - dev
jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: Install_Node_and_Packages
        run: |
            npm ci
            node ./cypress/prep_functions/page_fixture_creator.js
            npm run dev & wait-on http://localhost:3000
            npx cypress run --spec ./cypress/e2e/screenshots.cy.js
      - uses: actions/upload-artifact@v3
        with:
          name: Photos for recent PR GUI
          path: "**/cypress/screenshots/**/*.png"
